### ISSUE TITLE
这个版本还不如上个版本啊，识别成功率不是很高！

### ISSUE THREAD

**Issue by ldwonday** [wzc570738205/smartParsePro#1]
例如不支持
“湖北黄石市牧羊湖水机路华瑞南岸星城一栋二单元2502。刘红1898611114”
“
收货人: 杨艳
手机号码: 13682222221
所在地区: 广东省深圳市龙岗区龙岗街道
详细地址: 格水村三巷十号楼
”

**Comment by wzc570738205** [comment]
![image](https://user-images.githubusercontent.com/21350874/65784532-d65f1900-e184-11e9-98bf-1a7f658d9204.png)
这个版本不支持关键字过滤，只支持特殊字符过滤，不同的信息请用空格或者上述特殊字符（可自行添加）隔开
### 再说一句，你的手机号位数就不对（10位），试用前请先看下使用文档

**Comment by wzc570738205** [comment]
```湖北黄石市牧羊湖水机路华瑞南岸星城一栋二单元2502。刘红 18986111141```
```湖北黄石市牧羊湖水机路华瑞南岸星城一栋二单元2502。刘红。18986111141```
##### 只支持这样的格式!

**Comment by wzc570738205** [comment]
![image](https://user-images.githubusercontent.com/21350874/65784883-b67c2500-e185-11e9-951a-ac4cacd4bdd6.png)

**Comment by wzc570738205** [comment]
![image](https://user-images.githubusercontent.com/21350874/65785096-2b4f5f00-e186-11e9-970b-807b3dc80f40.png)
