### ISSUE TITLE
地址识别异常

### ISSUE THREAD

**Issue by gkxsn** [wzc570738205/smartParsePro#11]
福建省厦门市集美区后溪镇万科广场2号楼2601室 吴兴基 180******393

**Comment by wzc570738205** [comment]
电话不支持***，电话必须明文




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "wzc570738205/smartParsePro"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月16日(星期三) 下午5:52
收件人:&nbsp;"wzc570738205/smartParsePro"<smartParsePro@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[wzc570738205/smartParsePro] 地址识别异常 (#11)





 
福建省厦门市集美区后溪镇万科广场2号楼2601室 吴兴基 180******393
