### ISSUE TITLE
识别问题

### ISSUE THREAD

**Issue by easydowork** [wzc570738205/smartParsePro#13]
这个地址:黑龙江省 齐齐哈尔市 富裕县 富裕镇铁西区兴达街鑫春雷超市 
识别出来后是:
address:镇铁西区兴达街鑫春雷超市

**Comment by wzc570738205** [comment]
![image](https://user-images.githubusercontent.com/21350874/105665734-a491ca00-5f12-11eb-95d9-3bb821cf2af0.png)
地址不支持空格分开

**Comment by wzc570738205** [comment]
![](https://gitee.com/Wzhichao/img/raw/master/uPic/pQcrbT17%20.png)
