### ISSUE TITLE
address:  字段信息丢失内容

### ISSUE THREAD

**Issue by sytpb** [wzc570738205/smartParsePro#18]
address:  字段信息丢失内容

北京市海淀区西三旗建材城东二里13-2-502，李国强 1388888888

address: "西三旗建材城东二里13"
city: "北京市"
cityCode: "1101"
county: "海淀区"
countyCode: "110108"
name: "李国强"
phone: "1388888888"
province: "北京市"
provinceCode: "11"

13-2-502   内容不全，是不是把’-‘  当分隔符了？

**Comment by wzc570738205** [comment]
![image](https://user-images.githubusercontent.com/21350874/144772323-00b328f5-74ec-4f75-99cd-85f99c21ba48.png)
接口支持正常（电话少了一位）

**Comment by sytpb** [comment]
![image](https://user-images.githubusercontent.com/12178686/144774719-a4457456-f3f8-4117-b30c-580a0ea26cd2.png)


![image](https://user-images.githubusercontent.com/12178686/144774690-de6633f7-1e9a-46ac-8a44-4c9d3249fabf.png)

你好

我再次校验了一遍， 我的结果还是那样的，不是手机少一样的事，写成11位同样有这个问题。
（手机号是我为了屏蔽隐私替换了一下，写issue 里少写了一位）

然后完全一样的，我用你的Demo跑确实正常， 没有问题，我现在怀疑，是环境哪里的差异引起这个问题。 

另外 如果是少一位手机号，引起的话，那么在你的Demo 上运行，也应该复现我的问题，但实际上没有，虽然也出现了错误，但是不和我的错误不一样。见下图，可以和我的对比。

![image](https://user-images.githubusercontent.com/12178686/144775125-75081681-4ea3-48f3-abc2-3f3ef7aeb16f.png)

个人推断，应该是环境哪里差异引起了引问题，在我环境下跑和你的环境里跑结果是有差异的。

**Comment by wzc570738205** [comment]
> ![image](https://user-images.githubusercontent.com/12178686/144774719-a4457456-f3f8-4117-b30c-580a0ea26cd2.png)
> 
> ![image](https://user-images.githubusercontent.com/12178686/144774690-de6633f7-1e9a-46ac-8a44-4c9d3249fabf.png)
> 
> 你好
> 
> 我再次校验了一遍， 我的结果还是那样的，不是手机少一样的事，写成11位同样有这个问题。 （手机号是我为了屏蔽隐私替换了一下，写issue 里少写了一位）
> 
> 然后完全一样的，我用你的Demo跑确实正常， 没有问题，我现在怀疑，是环境哪里的差异引起这个问题。
> 
> 另外 如果是少一位手机号，引起的话，那么在你的Demo 上运行，也应该复现我的问题，但实际上没有，虽然也出现了错误，但是不和我的错误一样。见下图，可以和我的对比。
> 
> ![image](https://user-images.githubusercontent.com/12178686/144775125-75081681-4ea3-48f3-abc2-3f3ef7aeb16f.png)
> 
> 个人推断，应该是环境哪里差异引起了引问题，在我环境下跑和你的环境里跑结果是有差异的。

demo使用的是接口，支持更多地址，开源的支持地址少。

**Comment by wzc570738205** [comment]
> 同样的，我试了另一个开源开具，address-parse，没有遇到上面的问题，手机少一位也不会出现。
> 
> 仅供参考。

那个是之前的老版本，现在已经不维护了

**Comment by sytpb** [comment]
？？？    https://github.com/wzc570738205/smartParsePro  这也是老版本？  我不是新版本吗。晕了。
