### ISSUE TITLE
地址识别有误

### ISSUE THREAD

**Issue by cikenerd** [wzc570738205/smartParsePro#20]
待解析字符串：

> 张好[2568]
> 18411111111
> 广东省广州市南沙区东涌镇一建集团[2568]

实际解析结果

> 姓名:张好
> 
> 电话:18411111111
> 
> 邮编:
> 
> 省:广东省
> 
> 市:广州市
> 
> 区:南沙区
> 
> 街道:东涌镇
> 
> 详细地址:2568东涌镇一建集团

预期解析结果：

> 姓名:张好[2568]
> 
> 电话:18411111111
> 
> 邮编:
> 
> 省:广东省
> 
> 市:广州市
> 
> 区:南沙区
> 
> 街道:东涌镇
> 
> 详细地址:东涌镇一建集团[2568]

**期望待解析字符串2568放到详细地址和姓名末尾**

**Comment by wzc570738205** [comment]
目前的设计是使用特殊字符去过滤分割，不想切割`[`、`]`特殊字符可以修改此处的特殊字符
https://github.com/wzc570738205/smartParsePro/blob/c0f2662c8ad2c208ce262f2e8acc80b00dd34189/dist/address_parse.js#L399

**Comment by wzc570738205** [comment]
或者使用其他方式，比如在替换之前将`[`、`],`左括号`、右括号`之类的特殊定义汉字或者英文，然后再在结果里进行替换
