### ISSUE TITLE
无法通过npm 安装使用

### ISSUE THREAD

**Issue by Topgt** [wzc570738205/smartParsePro#26]
- 通过npm 下载的 "version": "2.0.2", 入口index.js文件没有export 任何方法
 - 看到您使用window.smart = smart; 暴露全局方法，但我这边使用服务端渲染，我的js运行时没有window对象。所有无法在服务端使用

**Comment by wzc570738205** [comment]
忘记了，我这就改改

**Comment by ShaoGongBra** [comment]
我也是这个问题，可以加一下导出

**Comment by wzc570738205** [comment]
> 我也是这个问题，可以加一下导出

`2.0.3`已修复
