### ISSUE TITLE
识别结果和示例里面不一样，识别不出姓名

### ISSUE THREAD

**Issue by ShaoGongBra** [wzc570738205/smartParsePro#27]
马云，陕西省西安市雁塔区丈八沟街道高新四路南江国际 13593464918

广东省珠海市香洲区盘山路28号幸福茶庄,陈景勇，13593464918

这个都识别不出来，看示例是能识别出来的

**Comment by wzc570738205** [comment]
`2.0.5`已修复

**Comment by wzc570738205** [comment]
https://codepen.io/wzc570738205/pen/RwrjLbq

![image](https://github.com/wzc570738205/smartParsePro/assets/21350874/8b68f91f-6eac-433d-bcfc-4147b2d360ae)
![image](https://github.com/wzc570738205/smartParsePro/assets/21350874/da0274ee-6a16-4375-9e50-0a204ef56256)
