### ISSUE TITLE
识别关联问题

### ISSUE THREAD

**Issue by recordque** [wzc570738205/smartParsePro#4]
输入‘广东省深圳市南区 ’，识别出的county:潮南区；countyCode:440514
vue引入也有类似问题 ：
输入‘广东省深圳市南山区 ’，识别出city: "深圳市"
cityCode: "4403"
county: "南山区"
countyCode: "230404"  //与广东深圳不关联
province: "广东省"
provinceCode: "44"

**Comment by wzc570738205** [comment]
![image](https://user-images.githubusercontent.com/33707245/76391789-2df7e680-63ab-11ea-96dd-decbac3ca5a6.png)
![image](https://user-images.githubusercontent.com/33707245/76391801-33edc780-63ab-11ea-9423-4650056ac914.png)
已修复
