### ISSUE TITLE
无法解析出地址，只能解析出姓名、号码、邮编、身份证

### ISSUE THREAD

**Issue by CrystalShen** [wzc570738205/smartParsePro#5]
项目中引入pcasCode.js、zipCode.js、address_parse.js后在页面中使用smart(“陕西省西安市雁塔区丈八沟街道高新四路高新大都荟710061 刘国良 13593464918 211381198512096810”),，仅返回{"zipCode":"710061","name":"刘国良","phone":"13593464918","idCard":"211381198512096810"}，没有返回地址解析结果。

**Comment by wzc570738205** [comment]
![image](https://user-images.githubusercontent.com/21350874/77735604-d661a800-7045-11ea-8e62-53aaa6c38c32.png)
http://wangzc.wang/smartParsePro/
