### ISSUE TITLE
识别结果有误

### ISSUE THREAD

**Issue by x1zbin** [wzc570738205/smartParsePro#8]
葛亚,13515842218,浙江省 宁波市 镇海区 蛟川街道临江小区30幢306室,315200
```js
{
    address: ""
    city: "宁波市"
    cityCode: "3302"
    county: "镇海区"
    countyCode: "330211"
    name: "蛟川街道临江小区30幢306室"
    phone: "13515842218"
    province: "浙江省"
    provinceCode: "33"
    zipCode: "315200"
}
```

**Comment by x1zbin** [comment]
反而旧的项目能正确识别[https://wzc570738205.github.io/smart_parse/](https://wzc570738205.github.io/smart_parse/)

**Comment by wzc570738205** [comment]
新版不支持地址分开输入

![image](https://user-images.githubusercontent.com/21350874/83103416-38dc3080-a0e9-11ea-9e32-a0b0ce5ae261.png)

**Comment by wzc570738205** [comment]
V4 已修复

<img width="1130" height="910" alt="Image" src="https://github.com/user-attachments/assets/eeb07649-c28b-44f7-bc60-d785613a8bc7" />
